#gcloud app deploy --version=v1-4
env: standard
runtime: python37
instance_class: F1
default_expiration: "10m"

automatic_scaling:
  max_instances: 1

handlers:
# site root
- url: /
  static_files: index.html
  upload: index.html
  
- url: /product
  static_files: template/shop-detail.html
  upload: template/shop-detail.html
  
- url: /blog
  static_files: blog/blog-post.html
  upload: blog/blog-post.html
  
- url: /(.*)
  static_files: \1
  upload: .*

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
